services:
  - type: web
    name: rb-sim-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server:start
    envVars:
      - key: NODE_VERSION
        value: 22
